<?php
    if($opc == "INF"){
     
?>
   <br/> <br/>
   <div class="info text-white bg-primary">
    <h2 class="text-center"> Quem Somos </h2>
    <h5> 
        Somos uma empresa que agencia aluguéis de filmes online, 
        temos no nosso catálogo filmes de ação, drama, terror, infantil e comédia, para todas as idades, 
        filmes casuais para ver com a familia ou mais sérios para impactar os telespectadores, filmes tanto atuais como antigos, 
        atualmente possuímos um total de 15 filmes. 
    </h5>
   </div>
   <br/> <br/>
   <div class="info text-white bg-primary">
    <h2 class="text-center"> Como Funcionamos </h2>
    <h5> 
        Nosso site é dividido em 4 partes: a página inicial onde o cliente pode consultar seu saldo atual,
        informações onde o cliente pode saber mais sobre a empresa e como ela funciona, filmes onde o cliente
        pode buscar os filmes que deseja por nome, elenco, genero, classificação, preço ou data de lançamento,
        restrito onde apenas os usuários que possuem a senha de entrada podem acessar para alterarem, excluírem ou 
        adicionarem filmes novos, e o carrinho onde o cliente ve os filmes que estão no seu carrinho, la ele pode alterar o número 
        de dias que o filme será alugado sendo que sempre que um filme é adicionado ao carrinho ele é inserido com o número de dias alugado 
        igual a 1 e o valor maximo de dias é 10, o cliente também pode excluir um o pedido do carrinho ou evazia-lo completamente caso mude de 
        ideia em relação a alugar X filme e por fim se tudo estiver conforme o cliente deseja ele pode efetuar sua compra. Após o cliente 
        confirmar sua compra ele é redirecionado para uma página que o informa se a compra foi efetuada com sucesso ou se ocorreu algum problema. 
        Lembrando sempre que os preços que são exibidos são o valor diário do aluguel do filme. 
    </h5>
   </div>
   <br/> <br/>
   <div class="info text-white bg-primary">
    <h2 class="text-center"> Descontos diponiveis </h2>
    <h5> 
        Atualmente possuímos 2 tipos de descontos: por valor total e por dias alugados. O desconto total funciona com compras acima 
        de 50 reais recebem 5% de desconto e compras acima de 100 reais recebem 10% de desconto. Já filme alugados por mais de 5
        recebem o desconto do valor diário do filme (ou seja se o cliente alugar um filme por 6 dias ele só pagará o valor do filme por 5 dias). 
    </h5>
   </div>
<?php
    }
?>